Update 57-2.cgel
nert-nlp/legal-cgel pull request #60
Opened 2024-10-04 18:29 UTC by mebwells

2024-11-12 17:20 UTC, bwaldon commented
@nschneid I think the comparative degree DPs _not more than 5,000_ + _not more than five_ have the correct constituency structure in light of discussion in CGEL (p. 432). I think we want to treat the numerals _5,000_ and _five_ as determinatives, in which case they're fused determiner-heads within their respective NPs?

2024-11-12 17:34 UTC, nschneid commented
Yeah that looks right

2024-12-20 18:09 UTC, nschneid commented
https://github.com/nert-nlp/cgel/issues/142

2025-02-08 05:18 UTC, nschneid requested changes
An insanely hard sentence! I only saw a couple of issues but am curious what kind of validation warnings will emerge

2025-02-08 05:18 UTC, nschneid commented on datasets/oneoff/usc-007.idbf2e9055-4f37-11ef-b6fb-9208f0a214ec_2_0.cgel
> +                                                    :Mod (PP
is this an agent phrase? if so, `:Comp`

2025-02-08 05:18 UTC, nschneid commented on datasets/oneoff/usc-007.idbf2e9055-4f37-11ef-b6fb-9208f0a214ec_2_0.cgel
> +                                                            :Head (Nom
need an additional Nom spanning the full NP

2025-02-10 18:34 UTC, merged